# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.SlugField(max_length=10, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.SlugField(max_length=10, unique=True, verbose_name='code')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.Province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.SlugField(unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geolocation.State', verbose_name='State'),
        ),
    ]
